### ISSUE TITLE
How to build without electronic background?

### ISSUE THREAD

**Issue by stevoh8494** [jnsbyr/esp8266-intexsbh20#1]
Hello, It's a really good work man, so again congratulations. I've the same spa and I'm really interested in connecting it to my home system.
But electronic is not my speciality. :( 

- How can I build it easily? 
- do you have references of each component used? 
- Do you have more pictures that can help me? 

Sorry, too much questions :)

**Comment by jnsbyr** [comment]
I am sorry, but if electronic is not your speciality I suggest you should not start with this project. And electronic skills will not be enough, you also need electromechanical skills for the watertight case and cables. Take the warning in the readme seriously. You have to create a reliable solution for the combination of water and electrical power. A pool should be a place for fun, so make sure to keep it that way. But it is not only about electrical safety. You should also know how to handle a multimeter and soldering iron, otherwise frustration is guaranteed.

If you feel you are up to the task you can simply use the component values from the schematic. All necessary info is included. Any good electronics retail will be able to supply them. In the photo of the perfboard you can even see how the components look like. There are no other photos. I never intended for anyone to rebuild it exactly in the same way. The idea was to show that it can be done. So you are free to use completely different components especially for the case and cables. If you need some more info, have a look at the solution for the other Intex models from [Geoffroy](https://github.com/yorffoeg/diyscip). Note that even with the necessary experience you will need around 2 working days for assembly and testing.

If you still want to continue, get yourself the required electronic components and a breadboard and make it work on your desk. This will probably take a while and it will get really messy when you try to connect the breadboard with the spa connector. Try to do it in the beginning without cutting into the cables of the spa, unlike I showed in the photo, but use a temporary solution. When I started with the hack, I placed very thin insulated wires with uninsulated ends into the female part of the plug of the control panel and fixed them in place by attaching the control panel again. With this kind of tap you can test your circuit and see what happens without mechanical damaging the spa. But this improvised tap has the disadvantage that you might easily short circuit the signal and power lines. I never tried to find out what happens. Maybe you will need a new spa mainboard.

I don't know anything about your capabilities so please don't take my explanation the wrong way. I hope it helps to put the project into the right perspective.
