### ISSUE TITLE
Just code for comunication with SBH-20

### ISSUE THREAD

**Issue by suplaseebee** [jnsbyr/esp8266-intexsbh20#50]
Hello,
I want to use your code to communicate with SUPLA DEVICE.
I don't want mqtt. Can you show me what can I delete in your code  and what  function i must use to change  temp, and on/off button etc.   (i just want to leave: common.h;   PureSpaIO.cpp;  PureSpaIO.h ) - if I leave just this it will be working good??

to on/off filter:
If (virtualbutton==1){ pureSpaIO.setFilterOn(true)};   // Is this correect?

or 
 to change temperature
int Tzad=36;
pureSpaIO.setDesiredWaterTempCelsius(Tzad); // Is this correct?

or 

to read actual temperature
int Tact= pureSpaIO.getActWaterTempCelsius();

or

to read actual state of filter pump
bool Pf;
pF= pureSpaIO.isFilterOn();

please help.  

You did a very very hard job  !!!
best seba.

**Comment by jnsbyr** [comment]
I am not sure I can put this in a nutshell, but I will try:

- Remove all files related to MQTT from the project, especial the MQTTClient.
- If you rebuild now, this will result in several errors. Start in esp8266-intexsbh20.ino by removing the code related to MQTT and replacing it with your code. 
- To make it easier you can write a wrapper class for the API you intend to use instead of MQTT. Use the same methods as defined in MQTTClient.h, but implement your own code. Then you can "just" rename the MQTTClient methods to your Wrapper Class. Basically MQTTClient is a wrapper class for the underlying pubsubclient API.

I will not be able to provide further in-depth help with your project. Have fun coding!
